apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: filesure
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.filesure.svc.cluster.local:9090
        isDefault: true
