apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: filesure
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # Scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Scrape Filesure API (always running)
      - job_name: 'filesure-api'
        static_configs:
          - targets: ['filesure-api-service.filesure.svc.cluster.local:5001']

      # Scrape Worker metrics (via Service on port 9100)
      - job_name: 'filesure-worker'
        scrape_interval: 15s
        static_configs:
          - targets: ['worker-service.filesure.svc.cluster.local:9100']
