apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: filesure
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
