apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: filesure
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # Scrape the API service
      - job_name: 'filesure-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['filesure-api-service:5001']

      # Scrape the Worker service (if at least one pod is running)
      - job_name: 'filesure-worker'
        metrics_path: /metrics
        static_configs:
          - targets: ['filesure-worker-service:9100']

      # Scrape Pushgateway (so even short-lived worker jobs are captured)
      - job_name: 'pushgateway'
        honor_labels: true
        static_configs:
          - targets: ['pushgateway:9091']
