apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: filesure
  labels:
    app: pushgateway
spec:
  selector:
    app: pushgateway
  ports:
    - name: http
      port: 9091
      targetPort: 9091
  type: ClusterIP
