apiVersion: v1
kind: Secret
metadata:
  name: filesure-secrets
  namespace: filesure
type: Opaque
stringData:
  MONGO_URI: "${MONGO_URI}"
  AZURE_STORAGE_ACCOUNT: "${AZURE_STORAGE_ACCOUNT}"
  AZURE_STORAGE_KEY: "${AZURE_STORAGE_KEY}"
  AZURE_CONTAINER_NAME: "${AZURE_CONTAINER_NAME}"
