apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: filesure-worker
  namespace: filesure
spec:
  jobTargetRef:
    template:
      spec:
        containers:
          - name: filesure-worker
            image: yasin445257/filesure-worker:latest
            envFrom:
              - secretRef:
                  name: filesure-secrets
            ports:
              - containerPort: 9100
                name: metrics
                protocol: TCP
        restartPolicy: Never
  pollingInterval: 30   # Check Mongo every 30s
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10
  triggers:
    - type: mongodb
      metadata:
        connectionStringFromEnv: MONGO_URI
        dbName: filesure
        collection: jobs
        query: '{"status":"pending"}'
        value: "1"
