apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: filesure
  labels:
    app: worker
spec:
  selector:
    app: worker
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
  type: ClusterIP
