apiVersion: v1
kind: Service
metadata:
  name: filesure-worker-service
  namespace: filesure
  labels:
    app: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
