apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: filesure-worker
  namespace: filesure
spec:
  pollingInterval: 10
  maxReplicaCount: 10
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  jobTargetRef:
    parallelism: 1
    completions: 1
    backoffLimit: 0
    ttlSecondsAfterFinished: 60
    template:
      spec:
        restartPolicy: Never
        containers:
          - name: worker
            image: yasin445257/filesure-worker:latest
            env:
              - name: MONGO_URI
                valueFrom:
                  secretKeyRef:
                    name: filesure-secrets
                    key: MONGO_URI
              - name: AZURE_BLOB_CONN
                valueFrom:
                  secretKeyRef:
                    name: filesure-secrets
                    key: AZURE_BLOB_CONN
              - name: AZURE_CONTAINER
                value: "documents"

  triggers:
    - type: mongodb
      metadata:
        connectionStringFromEnv: MONGO_URI
        dbName: filesure
        collection: jobs
        query: '{ "jobStatus": "pending" }'
        queryValue: "1"
